version: '2.1'

services:
  adminer:
    image: adminer:4.7
    container_name: adminer
    restart: always
    links:
      - mssql:mssql
    ports:
      - '${ADMINER_PORT:-8080}:8080'
    healthcheck:
      test: curl --silent http://localhost:8080 || exit 1
      interval: 10s
      timeout: 5s
      retries: 20
    # depends_on:
    #   postgres:
    #     condition: service_healthy
    #   mssql:
    #     condition: service_healthy
    #   mongodb:
    #     condition: service_healthy